// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home Page documents */
type HomePageDocumentData = Record<string, never>;
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
export type AllDocumentTypes = HomePageDocument;
/**
 * Primary content in PuppyBlock → Primary
 *
 */
interface PuppyBlockSliceDefaultPrimary {
    /**
     * Puppy Year field in *PuppyBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: puppy_block.primary.puppy_year
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    puppy_year: prismicT.TitleField;
}
/**
 * Item in PuppyBlock → Items
 *
 */
export interface PuppyBlockSliceDefaultItem {
    /**
     * Photo 1 field in *PuppyBlock → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: puppy_block.items[].photo_1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    photo_1: prismicT.ImageField<never>;
    /**
     * Puppy 2 field in *PuppyBlock → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: puppy_block.items[].puppy_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    puppy_2: prismicT.ImageField<never>;
    /**
     * Puppy 3 field in *PuppyBlock → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: puppy_block.items[].puppy_3
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    puppy_3: prismicT.ImageField<never>;
}
/**
 * Default variation for PuppyBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PuppyBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PuppyBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PuppyBlockSliceDefaultPrimary>, Simplify<PuppyBlockSliceDefaultItem>>;
/**
 * Slice variation for *PuppyBlock*
 *
 */
type PuppyBlockSliceVariation = PuppyBlockSliceDefault;
/**
 * PuppyBlock Shared Slice
 *
 * - **API ID**: `puppy_block`
 * - **Description**: `PuppyBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PuppyBlockSlice = prismicT.SharedSlice<"puppy_block", PuppyBlockSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomePageDocumentData, HomePageDocument, AllDocumentTypes, PuppyBlockSliceDefaultPrimary, PuppyBlockSliceDefaultItem, PuppyBlockSliceDefault, PuppyBlockSliceVariation, PuppyBlockSlice };
    }
}
