// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import Dog from './Dog';
import Hero from './Hero';
import Information from './Information';
import NavBar from './NavBar';
import NavigationItem from './NavigationItem';
import Puppies from './Puppies';

export {
	Banner,
	Dog,
	Hero,
	Information,
	NavBar,
	NavigationItem,
	Puppies,
};

export const components = {
	banner: Banner,
	dog: Dog,
	hero: Hero,
	information: Information,
	nav_bar: NavBar,
	navigation_item: NavigationItem,
	puppies: Puppies,
};
