// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import Dog from './Dog';
import Information from './Information';
import Puppies from './Puppies';

export {
	Banner,
	Dog,
	Information,
	Puppies,
};

export const components = {
	banner: Banner,
	dog: Dog,
	information: Information,
	puppies: Puppies,
};
